version: '0.2.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/ --verbosity m
build_script:
  # Package lib
  - cmd: dotnet build ./src/teesquare/teesquare.csproj --configuration=release
  - cmd: dotnet pack ../src/teesquare/teesquare.csproj --configuration=release
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\teesquare\bin\release\*.nupkg'
   name: Package
   type: NugetPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore --verbosity m
  # run the unit tests
  - cmd: dotnet test ./src/teesquare.tests/teesquare.tests.csproj
on_finish :
  # any cleanup in here
deploy: 
  provider: NuGet
  api_key: 
    secure: RkHFHd1enewSOYaQ4wnbpGG26YdP9vBMDGhSMMFO8Od9yUNC+smckUUXuC0lxdOO
  skip_symbols: true
  artifact: /.*\.nupkg/