version: '0.3.{build}-alpha'
image: Visual Studio 2017
branches:
  only:
  - master
  - feat/reflective-writer
  - feat/web-api
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/ --verbosity m
build_script:
  # Build lib
  - cmd: dotnet build ./src/teesquare.sln --configuration=release --no-restore
after_build:
  # For once the build has completed
  - cmd: dotnet pack ./src/teesquare/teesquare.csproj --configuration=release --no-restore
  - cmd: dotnet pack ./src/teesquare.webapi/teesquare.webapi.csproj --configuration=release --no-restore
artifacts:
 - path: '\src\teesquare\bin\release\*.nupkg'
 - path: '\src\teesquare.webapi\bin\release\*.nupkg'
   name: Package
   type: NugetPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/ --verbosity m
  # run the unit tests
  - cmd: dotnet test ./src/teesquare.tests/teesquare.tests.csproj
  - cmd: dotnet test ./src/teesquare.webapi.tests/teesquare.webapi.tests.csproj
on_finish :
  # any cleanup in here
deploy: 
  provider: NuGet
  api_key: 
    secure: RkHFHd1enewSOYaQ4wnbpGG26YdP9vBMDGhSMMFO8Od9yUNC+smckUUXuC0lxdOO
  skip_symbols: true
  artifact: /.*\.nupkg/