version: '3.3.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/ --verbosity m
build_script:
  # Build lib
  - cmd: dotnet build ./src/teesquare.sln --configuration=release --no-restore
after_build:
  # For once the build has completed
  - cmd: dotnet pack ./src/teesquare/teesquare.csproj --configuration=release --no-restore
  - cmd: dotnet pack ./src/teesquare.webapi/teesquare.webapi.csproj --configuration=release --no-restore
  - cmd: dotnet pack ./src/teesquare.webapi.core22/teesquare.webapi.core22.csproj --configuration=release --no-restore
  - cmd: dotnet pack ./src/teesquare.webapi.core31/teesquare.webapi.core31.csproj --configuration=release --no-restore
  - cmd: dotnet pack ./src/teesquare.mobx/teesquare.mobx.csproj --configuration=release --no-restore
artifacts:
 - path: '\src\teesquare\bin\release\*.nupkg'
 - path: '\src\teesquare.webapi\bin\release\*.nupkg'
 - path: '\src\teesquare.webapi.core22\bin\release\*.nupkg'
 - path: '\src\teesquare.webapi.core31\bin\release\*.nupkg'
 - path: '\src\teesquare.mobx\bin\release\*.nupkg'
   name: Package
   type: NugetPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/ --verbosity m
  # run the unit tests
  - cmd: dotnet test ./src/teesquare.tests/teesquare.tests.csproj
  - cmd: dotnet test ./src/teesquare.webapi.tests/teesquare.webapi.tests.csproj
  - cmd: dotnet test ./src/teesquare.mobx.tests/teesquare.mobx.tests.csproj
on_finish :
  # any cleanup in here
deploy: 
  provider: NuGet
  api_key: 
    secure: g7T/PUgacy6zYmJTVFpYow2U4d62R8q0X4KKpNxWj6ieQPUvHi1U2LOECMPr+fNE
  skip_symbols: true
  artifact: /.*\.nupkg/